global:

  scrape_interval: 5s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "rabbitmq"
    static_configs:
      - targets:
          - "rabbitmq:15692"
  - job_name: "sales-api"
    static_configs:
      - targets:
          - "sales-api:8090"
